// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wbjbvtaqkiczhlyzaupu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndiamJ2dGFxa2ljemhseXphdXB1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NTg0ODcsImV4cCI6MjA1OTIzNDQ4N30.hVD3AQHbK-tlKZ3xWzWOtto2IFb71h9-Ud_VmShr4BI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);